---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: whoami-sticky
    namespace: app
spec:
  entryPoints:
     - websecure
  routes:
    - kind: Rule
      match: Host(`s.waw.demo.traefiklabs.tech`)
      services:
        - kind: TraefikService 
          name: whoami-sticky-session
          namespace: app
  tls:
    certResolver: le           